include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    always_specify_types: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    public_member_api_docs: true
    # Add any additional rules you want to enforce
