name: traffica
description: A cross-platform intelligent mobility app built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.0
  dio: ^5.2.1
  fl_chart: ^0.63.0
  animations: ^2.0.9
  provider: ^6.1.0
  adaptive_theme: ^3.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.1
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#0b1220"
  android_12:
    color: "#ffffff"
    color_dark: "#0b1220"
  web: true

